version: '3'
services:
    api:
        image: golang
        container_name: fizzbuzz-api
        command: go run main.go
        volumes:
            - .:/go/src/fizzbuzz-api
            - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
        working_dir: /go/src/fizzbuzz-api
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            PRODUCTION_DATABASE: fizzbuzz-database
            TEST_DATABASE: fizzbuzz-test
        links:
            - database
    database: 
        image: mongo:latest
        container_name: fizzbuzz-mongo
        ports:
            - '27100:27017'