version: '3'
services:
    api:
        image: golang
        container_name: fizzbuzz-api
        command: go run main.go
        volumes:
            - .:/go/src/fizzbuzz-api
        working_dir: /go/src/fizzbuzz-api
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            REDIS_URL: redis:6379
        links:
            - database
    database: 
        image: mongo:latest
        container_name: fizzbuzz-mongo
        environment: 
            - MONGO_INITDB_DATABASE=fizzbuzz-database
        ports:
            - '27100:27017'